LibMan_c1627015m/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using LibMan_c1627015m.Models.DB;

namespace LibMan_c1627015m.Pages
{
    public class CreateModel : PageModel
    {
        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        public CreateModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["Username"] = new SelectList(_context.User, "Username", "Username");
            return Page();
        }

        [BindProperty]
        public Book Book { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Book.Add(Book);
            await _context.SaveChangesAsync();

            return RedirectToPage("./ListBook");
        }
    }
}

LibMan_c1627015m/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LibMan_c1627015m.Models.DB;

namespace LibMan_c1627015m.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        public DeleteModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Book Book { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Book = await _context.Book
                .Include(b => b.UsernameNavigation).FirstOrDefaultAsync(m => m.Id == id);

            if (Book == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Book = await _context.Book.FindAsync(id);

            if (Book != null)
            {
                _context.Book.Remove(Book);
                await _context.SaveChangesAsync();
            }

            //return RedirectToPage("./Index");
            return RedirectToPage("./ListBook");
        }
    }
}

LibMan_c1627015m/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LibMan_c1627015m.Models.DB;

namespace LibMan_c1627015m.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        public DetailsModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        public Book Book { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Book = await _context.Book
                .Include(b => b.UsernameNavigation).FirstOrDefaultAsync(m => m.Id == id);

            if (Book == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

LibMan_c1627015m/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibMan_c1627015m.Models.DB;

namespace LibMan_c1627015m.Pages
{
    public class EditModel : PageModel
    {
        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        public EditModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Book Book { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Book = await _context.Book
                .Include(b => b.UsernameNavigation).FirstOrDefaultAsync(m => m.Id == id);

            if (Book == null)
            {
                return NotFound();
            }
           ViewData["Username"] = new SelectList(_context.User, "Username", "Username");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Book).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookExists(Book.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./ListBook");
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.Id == id);
        }
    }
}

LibMan_c1627015m/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace LibMan_c1627015m.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

LibMan_c1627015m/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LibMan_c1627015m.Models.DB;
using Microsoft.AspNetCore.Http;

namespace LibMan_c1627015m.Pages
{
    public class IndexModel : PageModel
    {
        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        public string Password { get; set; }
        public string Msg { get; set; }

        public IndexModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        public IList<User> User { get; set; }

        public async Task OnGetAsync()
        {
            User = await _context.User.ToListAsync();
        }
        private bool UserExists(string Username, string password)
        {
            bool usern = false, pass = false;
            usern = _context.User.Any(e => e.Username == Username);
            pass = _context.User.Any(e => e.Password == password);
            if (usern == true && pass == true)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public IActionResult OnPost()
        {
            if (UserExists(Username, Password))
            {
                //HttpContext.Session.SetString("username", Username);
                var user = _context.User.Single(a => a.Username == Username);
                HttpContext.Session.SetString("Username", user.Username);
                // return RedirectToPage("Welcome");
                return RedirectToPage("Welcome");
            }
            else
            {
                Msg = "Invalid";
                return Page();
            }
        }

    }
}

LibMan_c1627015m/Pages/JSON.cshtml.cs
using System;
using System.IO;
using System.Text.Json;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Newtonsoft.Json.Linq;
using LibMan_c1627015m.Models.DB;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.VisualBasic.CompilerServices;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Formatters;
using LibMan_c1627015m.Models;

namespace LibMan_c1627015m.Pages
{
    public class JSONModel : PageModel
    {

        private readonly LibMan_c1627015m.Models.DB.libContext _context;
        private IWebHostEnvironment _environment;

        public JSONModel(LibMan_c1627015m.Models.DB.libContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public Book Book { get; set; }
        public string Username { get; set; }

        [BindProperty]
        public IFormFile File { get; set; }

        public IList<Book> Bookk { get; set; }

        public void OnGet()
        {

        }


        public void OnPostImport()
        {
            var path = Path.Combine(_environment.WebRootPath, "Upload", File.FileName);

            using (var f_stream = new FileStream(path, FileMode.Create))
            {
                f_stream.Position = 0;
                f_stream.Flush();
                File.CopyTo(f_stream);

            }

            using (StreamReader new_stream = new StreamReader(path))
            {
                string json = new_stream.ReadToEnd();
                JObject obj = JObject.Parse(json);
                JArray arr = (JArray)obj["Book"];
                IList<Book> books = arr.ToObject<IList<Book>>();
                string username = HttpContext.Session.GetString("Username");
                var userr = _context.User.Single(a => a.Username == username);
                foreach (var item in books)
                {
                    var book = new Book()
                    {
                       
                        Tittle = item.Tittle,
                        Author = item.Author,
                        Translator = item.Translator,
                        Publisher = item.Publisher,
                        BookDescription = item.BookDescription,
                        BookCover = item.BookCover,
                        Categories = item.Categories,
                        ReadingStatus = item.ReadingStatus,
                        Username = item.Username
                    };
                    _context.Book.Add(book);
                    _context.SaveChanges();
                }
            }
        }

        public void OnPostExport()
        {
            string name_of_file = Request.Form["File_Name"];
            string format = ".json";
            var path = Path.Combine(@"C:\Users\yildi\OneDrive\Masaüstü\export", name_of_file);
            var final_path = String.Concat(path, format);
            Username = HttpContext.Session.GetString("Username");
            Bookk = _context.Book.Where(b => b.Username == Username).ToList();
            string json = JsonConvert.SerializeObject(Bookk, Formatting.Indented);
            System.IO.File.WriteAllText(final_path, json);
        }
    }
}

LibMan_c1627015m/Pages/ListBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LibMan_c1627015m.Models.DB;
using Microsoft.AspNetCore.Http;

namespace LibMan_c1627015m.Pages
{
    public class ListBookModel : PageModel
    {
        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        public string Username { get; set; }

        public ListBookModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        public IList<Book> Book { get; set; }

        public async Task OnGetAsync()
        {
            Book = await _context.Book
                .Include(b => b.UsernameNavigation).ToListAsync();
            Username = HttpContext.Session.GetString("Username");
        }
    }
}

LibMan_c1627015m/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace LibMan_c1627015m.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

LibMan_c1627015m/Pages/SearchBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibMan_c1627015m.Models.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;

namespace LibMan_c1627015m.Pages
{
    public class SearchBookModel : PageModel
    {

        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        public string Tittle { get; set; }

        public SearchBookModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        public IList<Book> Book { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }
        public string Username { get; set; }

        public async Task OnGetAsync()
        {

            Username = HttpContext.Session.GetString("Username");
            var books = from b in _context.Book
                         select b;
            if (!string.IsNullOrEmpty(SearchString))
            {
                books = books.Where(s => s.Tittle.Contains(SearchString));
            }
            Book = await books.ToListAsync();
        }

        

      
    }
}

LibMan_c1627015m/Pages/SignUp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibMan_c1627015m.Models.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibMan_c1627015m.Pages
{
    public class SignUpModel : PageModel
    {
        private readonly LibMan_c1627015m.Models.DB.libContext _context;

        public SignUpModel(LibMan_c1627015m.Models.DB.libContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public User User { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.User.Add(User);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

LibMan_c1627015m/Pages/Welcome.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibMan_c1627015m.Pages
{

    public class WelcomeModel : PageModel
    {
        public string Username { get; set; }
        public string UserId;

        public void OnGet()
        {
            // UserId = User.FindFirst(ClaimTypes.Name).Value;
            Username = HttpContext.Session.GetString("Username");
        }
        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("Username");

            return RedirectToPage("Index");
        }
    }

}

LibMan_c1627015m/Pages/Create.cshtml
@page
@model LibMan_c1627015m.Pages.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_LayoutLogin.cshtml";
}

<h1>Add Book</h1>
<h3>You can add a new book to your library.</h3>
<hr />

<form method="post">
    <div class="form-row">
        <div asp-validation-summary="ModelOnly" class="text-danger" style="color:red"></div>
        <div class="form-group col-md-6">

            <label asp-for="Book.Username" class="control-label"></label>
            <select asp-for="Book.Username" class="form-control" asp-items="ViewBag.Username"></select>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Book.Tittle" class="control-label"></label>
            <input asp-for="Book.Tittle" class="form-control" />
            <span asp-validation-for="Book.Tittle" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Book.Author" class="control-label"></label>
        <input asp-for="Book.Author" class="form-control" />
        <span asp-validation-for="Book.Author" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Book.Translator" class="control-label"></label>
        <input asp-for="Book.Translator" class="form-control" />
        <span asp-validation-for="Book.Translator" class="text-danger"></span>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Book.Publisher" class="control-label"></label>
            <input asp-for="Book.Publisher" class="form-control" />
            <span asp-validation-for="Book.Publisher" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Book.BookDescription" class="control-label"></label>
            <input asp-for="Book.BookDescription" class="form-control" />
            <span asp-validation-for="Book.BookDescription" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="Book.Categories" class="control-label"></label>
            <input asp-for="Book.Categories" class="form-control" />
            <span asp-validation-for="Book.Categories" class="text-danger"></span>
            
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Book.ReadingStatus" class="control-label"></label>
            <input asp-for="Book.ReadingStatus" class="form-control" />
            <span asp-validation-for="Book.ReadingStatus" class="text-danger"></span>
            </label>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Book.BookCover" class="control-label"></label>
            <input asp-for="Book.BookCover" class="form-control" />
            <span asp-validation-for="Book.BookCover" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">add</button>
</form>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibMan_c1627015m/Pages/Delete.cshtml
@page
@model LibMan_c1627015m.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_LayoutLogin.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row" style="background-image:url(image/kitap4.jpg)">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Tittle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Tittle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Translator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Translator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Publisher)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Publisher)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.BookDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.BookDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.BookCover)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.BookCover)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Categories)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Categories)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.ReadingStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.ReadingStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.UsernameNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.UsernameNavigation.Username)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Book.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

LibMan_c1627015m/Pages/Details.cshtml
@page
@model LibMan_c1627015m.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_LayoutLogin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Tittle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Tittle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Translator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Translator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Publisher)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Publisher)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.BookDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.BookDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.BookCover)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.BookCover)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Categories)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Categories)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.ReadingStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.ReadingStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.UsernameNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.UsernameNavigation.Username)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Book.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

LibMan_c1627015m/Pages/Index.cshtml
@page
@model LibMan_c1627015m.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    @Model.Msg
    <form method="post" asp-page="login">
        <div class="form-group">
            <label for="exampleDropdownFormEmail2">Username</label>
            <input type="text" name="username" />
        </div>
        <div class="form-group">
            <label for="exampleDropdownFormPassword2">Password</label>
            <input type="password" name="password" />
        </div>
        <div class="form-group">
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="dropdownCheck2">
                <label class="form-check-label" for="dropdownCheck2">
                    Remember me
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <a class="btn btn-primary" asp-area="" asp-page="/SignUp" role="button">SignUp</a>
        </a>
    </form>





    @*<form method="post" asp-page="login">
        Username <input type="text" name="username" />
        <br />
        Password <input type="password" name="password" />
        <br />
        <input type="submit" value="Login" />
    </form>*@



</body>
</html>

LibMan_c1627015m/Pages/JSON.cshtml
@page
@model LibMan_c1627015m.Pages.JSONModel

@{
    ViewData["Title"] = "JSON";
    Layout = "~/Pages/Shared/_LayoutLogin.cshtml";
}

<!DOCTYPE html>

<html>
<body class="bg-white">

    <form method="post" action="" enctype="multipart/form-data">


        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <input type="file" id="file" asp-for="File" class="custom-file-input form-control" />
                        <label for="file" class="custom-file-label"> Choose your JSON file</label>

                        <p class="card-text"><small class="text-muted "> <button type="submit" class="bstyle btn btn-danger" asp-page-handler="Import">Import</button></small></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <label for="File_Name" class="lbltext">Enter your export name</label>
                        <input type="text" class="bstyle6" name="File_Name" id="File_Name" />

                        <p class="card-text"><small class="text-muted"> <button type="submit" class="bstyle btn btn-danger" asp-page-handler="Export">Export</button></small></p>
                    </div>
                </div>
            </div>
        </div>
    </form>





        <hr />
       

        <script>
            $(document).ready(function () {
                $('.custom-file-input').on('change', function () {
                    var fileName = $(this).val().split('\\').pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });</script>

</body>
</html>

LibMan_c1627015m/Pages/Welcome.cshtml
@page
@model LibMan_c1627015m.Pages.WelcomeModel
@{
    ViewData["Title"] = "Welcome";
    Layout = "~/Pages/Shared/_LayoutLogin.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Welcome</title>
</head>
<body>
    <div class="card bg-dark text-white" style="width:300px">
        <img src="~/image/reader.png" style="width:300px; height:300px; "    class="card-img" alt="...">
        <div class="card-img-overlay">
            <h5 class="card-title">Welcome @Model.Username</h5>
            <p class="card-text">This is a online library.</p>
        </div>
    </div>

   
    


</body>
</html>